//Problem #2
//Hammad Asad

//Problem Description:
/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/ 


public class Problem2{
  
  public static int fibonacciRecursion(int term1,int term2){
   if(term1>=4000000 || term2>=4000000) return 0;
   int temp=term2;
   term2+=term1;
   term1=temp;
   
   if(term1%2==0){
     return term1 + fibonacciRecursion(term1,term2);
   }else{
     return 0 + fibonacciRecursion(term1,term2); 
   }
 } 
 
 
 public static void main(String[] args){
 
   System.out.println("The sum of the even-valued terms under whose values don't exceed four million is : " + fibonacciRecursion(1,2)); 
   
 }

}